export const ACTIONS = {
    ADD_USERNAME: "ADD_USERNAME",
    RESTORE_USERNAME: "RESTORE_USERNAME",
    TOGGLE_ISREADY: "TOGGLE_ISREADY",
    TOGGLE_ISFINISHED: "TOGGLE_ISFINISHED",
    ADD_QUIZZMODE: "ADD_QUIZZMODE",
    ADD_QUESTIONS: "ADD_QUESTIONS",
    ADD_ANSWER: "ADD_ANSWER",
    RESTORE_GAME: "RESTORE_GAME"
}