export const ACTIONS = {
    ADD_USERNAME: "ADD_USERNAME",
    RESTORE_USERNAME: "RESTORE_USERNAME",
    TOGGLE_ISREADY: "TOGGLE_ISREADY",
    TOGGLE_ISFINISHED: "TOGGLE_ISFINISHED",
    ADD_QUIZMODE: "ADD_QUIZMODE",
    ADD_QUESTIONS: "ADD_QUESTIONS",
    ADD_ANSWER: "ADD_ANSWER",
    MINUS_SECONDS: "MINUS_SECONDS",
    RESTART_SECONDS: "RESTART_SECONDS",
    RESTORE_GAME: "RESTORE_GAME"
}